version: "3"
services:
  db:
    image: mysql:8.0.25
    container_name: jdbc-ex-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "manager"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/npee/repo/db/jdbc_ex:/var/lib/mysql